#FeelHome site branding
#Thu Sep 03 21:21:55 GMT+07:00 2026
site.heroBadge=FeelHome
site.name=FEELHOME
site.welcomeColor=\#d7b34f
site.welcomeEffect=shine
site.welcomeText=Ch\u00E0o m\u1EEBng \u0111\u1EBFn FeelHome
